### ISSUE TITLE
Добавить форму регистрации для пользователей

### ISSUE THREAD

**Issue by vrnsky** [we-are-comrades/billing#10]
Необходимо добавить для конечного пользователя форму регистрации

**Comment by vrnsky** [comment]
@OVakhnenko как ты думаешь каждый конечный пользователь должен иметь доступ к регистрации или лучше чтобы некий администратор создавал учетки?

**Comment by OVakhnenko** [comment]
можно при создании базы создать админа, а пользователи регистрируются сами, админ может учетки удалять, блокировать, менять пароль - мейл

**Comment by vrnsky** [comment]
@OVakhnenko да, давай так и сделаем

**Comment by vectree** [comment]
@vrnsky вы решили сделать вебку? 
На практике система была микросервисом, в который передавались данные извне.
Но, если интересно, то круто.

**Comment by vrnsky** [comment]
@vectree 
Да мы решали сделать web приложение. Два модуля - управление пользователями и менеджер транзакций. У меня может быть пока недостаточно опыта, чтобы направить проект в нужное русло. Списал с другим членом команды в вк, завтра должен будет ответить. Общение у нас организовано в gitter (we-are-comrades). Мне хотелось бы услышать как вы видите развитие проекта, а также как лучше декомпозировать задачи для нас.

**Comment by vrnsky** [comment]
@vectree нам также рекомендации по поводу фронта, потому что на данный момент, ни у кого из членов команды нет опыта с js фрэймворками. Я выступаю с angular или ext.js, 1-й потому, что пользуются в google, а второй потому, что используется для энтерпрайз приложений

**Comment by vrnsky** [comment]
@vectree отправил вам запрос на добавление вас в коллаборацию, чтобы была возможность запрашивать ваше code review

**Comment by OVakhnenko** [comment]
форму авторизации/регистрации и настройки spring security сегодня добавлю

**Comment by vectree** [comment]
@vrnsky можно сделать созвон в скайпе и пообщаться по поводу фронта и архитектуры.

**Comment by vectree** [comment]
@vrnsky, если не сложно, добавьте мой аккаунт. Ник: vladthelittleone.

**Comment by OVakhnenko** [comment]
@vrnsky можно, сегодня вечером?

**Comment by vrnsky** [comment]
@OVakhnenko сегодня вечером не могу, уезжаю на выходные.
@vectree это ваш аккаунт где github или skype? я просто вас ни тут, не там не нашел.
@vectree если не трудно, то напишите мне в gitter

**Comment by OVakhnenko** [comment]
@vrnsky я буду в командировке на следующей неделе, если после 20-ти удобно будет?

**Comment by vrnsky** [comment]
@OVakhnenko да, удобно. нашел теперь

**Comment by vrnsky** [comment]
@vectree отправил вам(vladthelittleone) в репозиторий.

**Comment by OVakhnenko** [comment]
@vrnsky формы логин/регистрация [здесь](https://github.com/we-are-comrades/billing/pull/17)

**Comment by vladthelittleone** [comment]
@OVakhnenko да, можно после 20. Кстати в гиттере не вижу чат и не могу зайти в него.

**Comment by vrnsky** [comment]
@vladthelittleone @OVakhnenko 
Скоро уже 20, давайте обсудим примерную дату.  Всех устроит 25-26 числа? И время. Предлагаю созвониться вечерком - между 18:00 и 21:00 часами по МСК

**Comment by OVakhnenko** [comment]
@vrnsky меня устроит
