### ISSUE TITLE
Добавить maven plugin jetty

### ISSUE THREAD

**Issue by vrnsky** [we-are-comrades/billing#7]
Надо сделать так, чтобы приложение запускалось с помощью jetty. Это позволит сократить время локального тестирования, а то Tomcat **пздц долго** как старует
Запуск приложения должен осуществлять командой ```mvn jetty:run```

**Comment by OVakhnenko** [comment]
billing не хотел подниматься по mvn jetty:run ругался - java.lang.IllegalStateException: Multiple servlets map to path... изменил настройки спринга -- поднялось.

**Comment by vrnsky** [comment]
resolved #13 by @OVakhnenko
