### ISSUE TITLE
Поднятие базы данных

### ISSUE THREAD

**Issue by vrnsky** [we-are-comrades/billing#8]
Сделать так, чтобы при запуске приложения, запускались sql скрипты из resources\sql\**
Схему тогда тоже переноси в папку со sql. Еще надо завести бин из спринга, который умеет общаться с базой, это по-моему ```jdbcNamedParameterTemplate``` или что-то такое

**Comment by OVakhnenko** [comment]
вопрос по Account:

    private Account account;
    //private Set<Account> accounts; может так?

**Comment by vrnsky** [comment]
@OVakhnenko  не совсем понимаю что ты хочешь сделать

**Comment by OVakhnenko** [comment]
у нас пользователь один, а счетов много, или я не совсем понял что будет в поле Account ?

public class User {
    private int id;
    private String email;
    private String password;
    private Account account;
}

в поле account какой счет будет храниться?

**Comment by vrnsky** [comment]
@OVakhnenko связь будет one-to-one, то есть у одного пользователя, только один аккаунт

**Comment by OVakhnenko** [comment]
[ok](https://github.com/we-are-comrades/billing/pull/15)

**Comment by OVakhnenko** [comment]
@Bean
public DataSource dataSource() {
    EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
    return builder.setType(EmbeddedDatabaseType.HSQL).
addScript("classpath:scripts/create-table-if-not-exists").build();
}

подойдет для инициализации БД?

**Comment by vrnsky** [comment]
@OVakhnenko да подойдет, надо только подумать как разделить прод и тест. Потому что условно на проде postgres, а для тестирования hsql

**Comment by vrnsky** [comment]
Закроется при слиянии #32
