### ISSUE TITLE
Реализовать CRUD операции с сущностью пользователь

### ISSUE THREAD

**Issue by vrnsky** [we-are-comrades/billing#9]
Надо написать реализацию CRUD репозитория для работы с сущностью пользователя.
В репозиторий должны присутствовать следующие методы:
```
add(User user); //Добавляет нового пользователя в бд
edit(User user); //Обновляет данные об уже существующем пользователе
getUserById(int id); //Возвращает инстанст объекта или null
List<User> list(); //возвращает список всех пользователей
```

**Comment by OVakhnenko** [comment]
@vrnsky [тут](https://github.com/we-are-comrades/billing/pull/15) и [тут](https://github.com/we-are-comrades/billing/pull/16)

**Comment by vrnsky** [comment]
Resolved via 5d565e3212eb
